### ISSUE TITLE
Compress images for front page

### ISSUE THREAD

**Issue by philpax** [awaycollective/awaycollective.github.io#2]
The front page uses the full-resolution images, which requires more bandwidth than is desirable. Should be possible to process the images and generate smaller thumbnails: https://www.getzola.org/documentation/content/image-processing/

**Comment by centuryglass** [comment]
Two questions:
1. Any preference regarding the specific resolution/format/scaling mode of the thumbnails?
2. Should the full-size version of the image load immediately when clicked, or should I add a link in the expanded view to the full-resolution image?

**Comment by philpax** [comment]
1. They should be around the same perceived resolution on the main page; hard to say exactly what that is, given that it depends on the client's resolution, but I'd try a bunch of numbers and stop once you can see a noticeable loss in quality. Ideally, all of the images together add up to a few hundred kilobytes at most.
2. I think it's fine if the full-size images loads on click. I haven't looked too closely at how the gallery expansion works (we inherited this website), but my hope is that the browser doesn't load images that are `display: none` by default, and you can just have the URL to the full-size image in there without having to write additional JS (i.e. switching the modal away from `display: none` is sufficient to trigger the full-size load)

**Comment by philpax** [comment]
Done by #5.
